# Generated by Django 4.2.10 on 2024-09-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='urgency',
            field=models.CharField(choices=[('now', 'Now'), ('best_time', 'BestTime'), ('later', 'Later'), ('never', 'Never')], default='never', max_length=50),
        ),
    ]
