# Generated by Django 4.2.10 on 2024-08-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='upvote',
            field=models.IntegerField(default=0),
        ),
    ]
