# Generated by Django 4.2.10 on 2024-06-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
