# Generated by Django 4.2.10 on 2024-06-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_business_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
